### ISSUE TITLE
Fully Parse XML Documents in the ETL

### ISSUE THREAD

**Issue by mawburn** [mawburn/portaler-core#62]
Currently we only pull from the world.json in [broderickhyman/ao-bin-dumps](https://github.com/broderickhyman/ao-bin-dumps/blob/master/cluster/world.json) and use that to populate our database. 

However, within this file each entry contains a link to an `.xml` file, that can lead you down a rabbit hole of basically all the information there is to find about a zone. Such as mobs, chest tiers, crafting tiers, refine rates, etc. 

This would close issues like #55, but Intel in #61 could serve as an interim solution for that. However, both are needed.

**Comment by reznok** [comment]
I've done a lot of this work already for some ROAM API stuff. It's god awful code, but it shows how to access the various information including roads chest tiers as well as dungeon tier and types. 

The code is gross, but can be found at:
https://gist.github.com/reznok/d6a80697983df2fece3bd77cfc0a77c7

Still needs to be rewritten into TS for Portaler, but hopefully this helps kick start the work for someone.

Example of what using this data looks like on the ROAM API:
https://albion.reznok.com/api/roads?name=Puros-Ofavam

**Comment by mawburn** [comment]
Thanks @reznok! 

I tell you what. If you can show me a way to cleanly parse and type of XML that we have to use to get the right data from these files, I'll pay ROAMs server costs for 6mo. lol

(Kidding btw, because it's impossible)

**Comment by mawburn** [comment]
Also if you ever wanna learn you some TS, I know a good project looking for contributors! 😁
