### ISSUE TITLE
Move from Subdomains to Path based

### ISSUE THREAD

**Issue by mawburn** [mawburn/portaler-core#64]
Currently we use subdomains for servers, instead of path based routing. We should move to path based routing for multiple reasons. 

1. It would allow us to create a method for users to sign up for themselves, because we don't have to interface with Cloudflare.
2. It would allow us to add advertising to the pages.
3. It would probably allow us to merge servers easier, so multiple servers could use the same map. (this requires more thought)

**Comment by mawburn** [comment]
So, my suggestion to do this is to move the routes to just a path like:

https://portaler.zone/s/yourservername

And I or whoever is hosting it can route this with NGINX rule.

**Comment by SandroMoretti** [comment]
Hum, my idea its to create an interface who list only the servers that I'm and have portaler installed.


I have an similar software that I developed to my ally make bets in an 1v1 tourment. Look the example:

https://user-images.githubusercontent.com/6597833/141595321-362a67b4-a584-4627-ac4d-c786f7444fda.mp4


Its very similar to portaler interface. But when I loggin, I have to select what server I want to use. If I have only 1 server it will come selected as default. This way I dont need subdomain or url paths, but if I want to put an subdomain (only for have my ally in url) I can, will have no diffs 😄 

This way is a bit more hard to do, but I guess the result its very good.

**Comment by mawburn** [comment]
Copy and pasting this from a Discord chat with @fastFox2 

```
hypnoCode — Today at 9:55 AM
So to make it path based, you're going to have to add paths in the React Router that are like /g/:name so the url would be like portaler.zone/g/myguild 

A lot of the other parts are already setup do go somewhere like this, they just need to be changed from going to a subdomain to a /g/:name location. 

In the frontend, when you go to login, it sets a localstorage or a cookie value with the sumdomain to redirect to. This is because when you come back from auth, it actually redirects back to auth.portaler.zone not yourname.portaler.zone because the way oauth works is that you need to set that up. However, this can be killed off because the domain will be fine and you can just add the variable to the redirect in auth. Sounds more complicated than it actually is. The current way is more complicated.

Then the hardest part would be adjusting the auth validator to validate the path, instead of the subdomain. This could be hard or it could be easy. I'm not really sure and it's just one of those things I can't really guess at without actually doing it. Either way though, it shouldn't be super complicated. 

For the rest of it, I can do that myself in the server. I will just redirect the /g/ stuff to the api layer, so adding that /g/ is very important. It also avoids conflicts if you ever want to add to the website for tutorials and stuff.
[9:55 AM]
I would go with /g/ for group
```
