### ISSUE TITLE
Move Connections back to Radio

### ISSUE THREAD

**Issue by mawburn** [mawburn/portaler-core#68]
Originally I had Radios and I thought it was bad design, so I moved it to buttons. Turns out, people hate this. I haven't had the time to move it back. The code should be in the history, so this shouldn't be a difficult task.

Currently we have this:

<img width="282" alt="Screen Shot 2021-08-08 at 7 33 48 PM" src="https://user-images.githubusercontent.com/2829924/128648944-a7698f2f-7b4c-4a5b-aa59-62b367c77b34.png">

We need to move back to this:

<img width="300" alt="Screen Shot 2021-08-08 at 7 34 51 PM" src="https://user-images.githubusercontent.com/2829924/128648947-d5aa0793-9df6-4555-a6c8-b2f5e90861df.png">

(except keeping the royal connections)

**Comment by Tyrben** [comment]
This transformation was done in v0.2.0 "UI Rework" with other sub-features. 93a620bc
My guess: PortalForm/PortalSizeSelector.tsx is the only file to retake.
&hover and &disabled can be retaken back to &checked

**Comment by mawburn** [comment]
@Tyrben that sounds about right! Thanks for providing info. 

Can you tell me who you are on Discord?

**Comment by Tyrben** [comment]
I'm Balladur, yeah, I never have the same alias, even this one is from EVE online, years ago :)
