### ISSUE TITLE
Store User Settings on Server

### ISSUE THREAD

**Issue by mawburn** [mawburn/portaler-core#72]
Need to create a table, the user settings could just be a JSONB object. 

We only have 1 setting now, which is the user's home.

**Comment by fastFox2** [comment]
I'm planning to add another Setting, whether the user prefers radios or buttons for the portal size.

**Comment by mawburn** [comment]
If you want, you use that to tackle this ticket to store user preferences on the server instead of localStorage. Or you could just put that in localStorage.
