### ISSUE TITLE
Add Unit Tests

### ISSUE THREAD

**Issue by mawburn** [mawburn/portaler-core#74]
So... we have no tests. Well, I think we have one. That's bad. We need tests. 

This is a ticket that will probably live in TODO for a long time, even if we get a lot of contributor support. Jest is what we should be using and they should be in TS.

---

Edits:

Homepage doesn't need unit tests at all. It's just a Gatsby page.

For the rest of the stuff, see the comments below on how to best structure them. 

The Bot is getting redesigned to use the API in #48 (if I ever finish it), so we can probably skip that for now.

**Comment by Tyrben** [comment]
The tests are localized aside of their tested target? 
I see only one example: zoneSearchUtils.test.ts
Is that correct?

**Comment by mawburn** [comment]
Good question @Tyrben, yes for React components or things that are split off into files, they should be localized. 

---

But I think tests for the API is the most important place for unit tests for the components or anything on the frontend. For the API I would prefer a singular `/packages/api-server/tests/*` folder rather than making those localized.

---

For the `/shared` packages, best judgement. For like `/shared/data-models/src/models` those should probably be split off into folders where the unit tests are local to the model it's testing, then an index that is either the model or exports the model (developer's choice if someone picks that up). 

ie: 

* `/shared/data-models/src/models/Server/index.ts`
* `/shared/data-models/src/models/Server/Server.ts`
* `/shared/data-models/src/models/Server/Server.test.ts`

or

* `/shared/data-models/src/models/Server/index.ts`
* `/shared/data-models/src/models/Server/Server.test.ts`

Either way is fine.
