### ISSUE TITLE
Make Self Hosting Easier

### ISSUE THREAD

**Issue by mawburn** [mawburn/portaler-core#75]
We have a pretty good [tutorial for self hosting](https://github.com/Portaler-Zone/portaler-core/blob/main/selfhosting.md) by @ImmortalBrain, but we could make it easier by providing `docker-compose.yml` files that are drag and drop and maybe supporting a single a way to merge services into a single Docker container, [which I had once](https://github.com/Portaler-Zone/portaler-core/blob/82902f3310dd453b4d0097207feef5d7cd68ba5f/docker/local.dockerfile), but dropped because I wasn't keeping it up to date and juggling keys became hard.

**Comment by Logoffski** [comment]
I guess [this](https://github.com/Logoffski/portaler-core/tree/docker_test/docker) kinda belongs here.
Obviously this is far away from being a complete solution, but the docker-compose file is "done" and I'll be working on the install script when i have the time.
