### ISSUE TITLE
Failed to compile - Ubuntu Server 20.04.3

### ISSUE THREAD

**Issue by NewFake** [mawburn/portaler-core#85]
Trying to run localy. I get this after everything goes ok:
![PortalerError](https://user-images.githubusercontent.com/28830055/134810033-f0a3cc12-dcae-4ffd-8c16-f1005fc0be13.png)

**Comment by fastFox2** [comment]
Did you run `yarn build:shared && yarn` before? I know, it's not documented, but it fixed it for me.

**Comment by mawburn** [comment]
If this is the issue, can you make a PR for that @NewFake to update the documentation? That would be awesome.

**Comment by NewFake** [comment]
Went to the process again. Ran `yarn build:shared && yarn` after `yarn install` and everything was ok, now the page opens.

I'm sorry mawburn, but kinda new to github, don't really know i to do a PR
